import type { ClientData, Store } from "./types";
import { blankData, uid } from "./normalize";

function ventoSul(): ClientData {
  const d = blankData("Vento Sul Importação Ltda.");
  d.meta.accountManager = "F. — Trading Desk";
  d.meta.period = "July 2026";
  d.meta.issued = "05 Aug 2026";
  d.meta.reportNo = "VS·ASR·2026-07";
  d.kpi.activeFoot = "▲ 2 vs. Jun";
  d.kpi.transitFoot = "next ETA 19 Aug · Paranaguá";
  d.pos = [
    {
      id: uid(),
      code: "PO-2026-0151",
      ndr: "NDR-2601",
      product: "Paper cups 8oz DW",
      qty: "1.15M pcs",
      value: 98900,
      incoterm: "FOB Qingdao",
      prod: 5,
      insp: "Pending",
      inspDate: "",
      cargoReady: "12 Sep",
      eta: "18 Oct",
      port: "Santos",
      stage: "Confirmed",
    },
    {
      id: uid(),
      code: "PO-2026-0149",
      ndr: "NDR-2602",
      product: "Cornstarch clamshells",
      qty: "2×40′HC",
      value: 71200,
      incoterm: "FOB Shenzhen",
      prod: 60,
      insp: "Booked",
      inspDate: "22 Aug",
      cargoReady: "30 Aug",
      eta: "05 Oct",
      port: "Santos",
      stage: "In Production",
    },
    {
      id: uid(),
      code: "PO-2026-0148",
      ndr: "NDR-2603",
      product: "Bamboo stirrers",
      qty: "6.0M pcs",
      value: 75000,
      incoterm: "FOB Ningbo",
      prod: 80,
      insp: "Booked",
      inspDate: "18 Aug",
      cargoReady: "26 Aug",
      eta: "01 Oct",
      port: "Paranaguá",
      stage: "In Production",
    },
    {
      id: uid(),
      code: "PO-2026-0146",
      ndr: "NDR-2604",
      product: "Paper straws",
      qty: "3.2M pcs",
      value: 41600,
      incoterm: "FOB Ningbo",
      prod: 100,
      insp: "Booked",
      inspDate: "08 Aug",
      cargoReady: "15 Aug",
      eta: "20 Sep",
      port: "Santos",
      stage: "Inspection",
    },
    {
      id: uid(),
      code: "PO-2026-0145",
      ndr: "NDR-2605",
      product: "Kraft food boxes",
      qty: "2×40′HC",
      value: 88400,
      incoterm: "FOB Qingdao",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "Ready 06 Aug",
      eta: "12 Sep",
      port: "Itajaí",
      stage: "Cargo Ready",
    },
    {
      id: uid(),
      code: "PO-2026-0144",
      ndr: "NDR-2606",
      product: "Sugarcane bowls",
      qty: "1×40′HC",
      value: 46700,
      incoterm: "FOB Qingdao",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "Booked 05 Aug",
      eta: "10 Sep",
      port: "Santos",
      stage: "Booked",
    },
    {
      id: uid(),
      code: "PO-2026-0143",
      ndr: "NDR-2607",
      product: "PLA cutlery sets",
      qty: "1×40′HC",
      value: 52300,
      incoterm: "FOB Shenzhen",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "Loaded 02 Aug",
      eta: "08 Sep",
      port: "Santos",
      stage: "Loaded",
    },
    {
      id: uid(),
      code: "PO-2026-0141",
      ndr: "NDR-2608",
      product: "Paper cups 12oz",
      qty: "0.90M pcs",
      value: 79200,
      incoterm: "CIF Santos",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "ETD 19 Jul",
      eta: "24 Aug",
      port: "Santos",
      stage: "In Transit",
    },
    {
      id: uid(),
      code: "PO-2026-0140",
      ndr: "NDR-2609",
      product: "Bagasse plates",
      qty: "30 CBM",
      value: 63700,
      incoterm: "FOB Qingdao",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "ETD 14 Jul",
      eta: "19 Aug",
      port: "Paranaguá",
      stage: "In Transit",
    },
  ];
  d.neg = [
    {
      id: uid(),
      ref: "NEG-04",
      topic: "Kraft mailer boxes — new SKU",
      next: "send FOB quote",
      owner: "Desk",
      due: "08 Aug",
      value: 120000,
      stage: "Inquiry",
      outcome: "Open",
      samples: "Pending",
    },
    {
      id: uid(),
      ref: "NEG-03",
      topic: "Cornstarch cutlery — volume tier",
      next: "align target price",
      owner: "Client",
      due: "11 Aug",
      value: 260000,
      stage: "Proposal",
      outcome: "Open",
      samples: "Approved",
    },
    {
      id: uid(),
      ref: "NEG-02",
      topic: "Bamboo stirrers — H2 re-price",
      next: "counter w/ 2 factories",
      owner: "Desk",
      due: "07 Aug",
      value: 150000,
      stage: "Proposal",
      outcome: "Open",
      samples: "Delivered",
    },
    {
      id: uid(),
      ref: "NEG-01",
      topic: "Annual paper-cup framework",
      next: "draft agreement",
      owner: "Desk",
      due: "14 Aug",
      value: 520000,
      stage: "Proposal",
      outcome: "Open",
      samples: "Approved",
    },
    {
      id: uid(),
      ref: "NEG-99",
      topic: "Sugarcane trays — spot deal",
      next: "— converted to PO-0144",
      owner: "Desk",
      due: "—",
      value: 46700,
      stage: "Proposal",
      outcome: "Won",
      samples: "Approved",
      wonPo: "seeded",
    },
    {
      id: uid(),
      ref: "NEG-98",
      topic: "Wooden forks — bulk trial",
      next: "— price not competitive",
      owner: "Desk",
      due: "—",
      value: 60000,
      stage: "Inquiry",
      outcome: "Lost",
      samples: "Rejected",
    },
  ];
  d.act = [
    {
      id: uid(),
      type: "red",
      text: "PO-0146 — QC window is tight. Confirm inspection booking by 08 Aug to protect 15 Aug cargo-ready date.",
      owner: "Trading Desk",
    },
    {
      id: uid(),
      type: "client",
      text: "PO-0145 — cargo ready 06 Aug. Awaiting booking confirmation & shipping instructions from client.",
      owner: "Client",
    },
    {
      id: uid(),
      type: "blue",
      text: "PO-0143 — loaded 02 Aug; vessel booked, ETD confirmed 08 Sep to Santos.",
      owner: "Trading Desk",
    },
    {
      id: uid(),
      type: "gold",
      text: "PO-0151 — deposit received 01 Aug; production start pending material colour approval.",
      owner: "Factory / Client",
    },
    {
      id: uid(),
      type: "grn",
      text: "NEG-01 — client requested payment-terms review (30/70 → LC at sight) before signing.",
      owner: "Trading Desk",
    },
  ];
  d.closed = [
    {
      id: uid(),
      code: "PO-2026-0138",
      ndr: "NDR-2588",
      product: "Bagasse bowls",
      value: 58900,
      delivered: "28 Jul",
      port: "Santos",
    },
    {
      id: uid(),
      code: "PO-2026-0135",
      ndr: "NDR-2585",
      product: "Paper cups 16oz",
      value: 84300,
      delivered: "15 Jul",
      port: "Itajaí",
    },
  ];
  return d;
}

function andes(): ClientData {
  const d = blankData("Andes Importações S.A.");
  d.meta.period = "July 2026";
  d.meta.issued = "05 Aug 2026";
  d.meta.reportNo = "AND·ASR·2026-07";
  d.meta.tradeLane = "China → Chile (CL)";
  d.pos = [
    {
      id: uid(),
      code: "PO-2026-0207",
      ndr: "NDR-2610",
      product: "PET clamshells",
      qty: "2×40′HC",
      value: 64800,
      incoterm: "FOB Ningbo",
      prod: 35,
      insp: "Pending",
      inspDate: "",
      cargoReady: "20 Sep",
      eta: "28 Oct",
      port: "San Antonio",
      stage: "In Production",
    },
    {
      id: uid(),
      code: "PO-2026-0205",
      ndr: "NDR-2611",
      product: "Aluminium foil trays",
      qty: "1×40′HC",
      value: 47500,
      incoterm: "FOB Qingdao",
      prod: 100,
      insp: "Passed",
      inspDate: "",
      cargoReady: "Loaded 03 Aug",
      eta: "09 Sep",
      port: "San Antonio",
      stage: "Loaded",
    },
  ];
  d.neg = [
    {
      id: uid(),
      ref: "NEG-11",
      topic: "Compostable cups — trial order",
      next: "send samples",
      owner: "Desk",
      due: "12 Aug",
      value: 90000,
      stage: "Inquiry",
      outcome: "Open",
      samples: "Requested",
    },
  ];
  d.closed = [
    {
      id: uid(),
      code: "PO-2026-0198",
      ndr: "NDR-2580",
      product: "Kraft bags",
      value: 39900,
      delivered: "22 Jul",
      port: "Valparaíso",
    },
  ];
  return d;
}

/** Identical to HTML seedStore(). */
export function seedStore(): Store {
  const c1 = { id: uid(), data: ventoSul() };
  const c2 = { id: uid(), data: andes() };
  return {
    activeClientId: c1.id,
    clients: [c1, c2],
    logo: null,
    settings: { deliveredMode: "Hidden" },
  };
}
